services:

  # ==========================================
  # Base de datos PostgreSQL
  # ==========================================
  db:
    image: postgres:16-alpine
    container_name: aventureros-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestion_procesos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestion_procesos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # Backend Spring Boot
  # ==========================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aventureros-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://jdbc:postgresql://190.146.2.119:2345/postgres
      SPRING_DATASOURCE_USERNAME: grupo13_user
      SPRING_DATASOURCE_PASSWORD: G13#tR6!Qw2$Lm9@Xp8V
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    name: aventureros-postgres-data
