spring.application.name=backend

# Conexión al servidor IP de grupo 13
spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/grupo13
spring.datasource.username=grupo13_user
# NOTA: ENMASCARAR CONTRASEÑA
spring.datasource.password=G13#tR6!Qw2$Lm9@Xp8V

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestión o manejo de las tablas 
# Se usa 'update' para que Spring cree las tablas del DER automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# Configuración Servidor de Correo (Gmail SMTP Ej)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=p45910458@gmail.com
# ¡IMPORTANTE! Genera tu Contraseña de Aplicación en Google y reemplaza el texto de abajo
spring.mail.password=bjesshtprjvtbclw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true