spring.application.name=backend

# Conexión al servidor IP de grupo 13
spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/postgres
spring.datasource.username=grupo13_user
spring.datasource.password=PASSWORD_GRUPO13

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestión o manejo de las tablas 
# Se usa 'update' para que Spring cree las tablas del DER automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true